name: Delete S3 Medallion Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirm_delete:
        description: 'Type "DELETE" to confirm stack teardown'
        required: true
        default: "NO"

jobs:
  delete-stack:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Empty S3 Bucket (Required before deletion)
        run: |
          BUCKET_NAME=$(aws s3 ls | grep sentinel-fraud-detection-datalake | awk '{print $3}')

          if [ -n "$BUCKET_NAME" ]; then
            echo "Found bucket: $BUCKET_NAME. Starting recursive deletion..."
            # Remove all versions (important since versioning is enabled)
            aws s3 rb s3://$BUCKET_NAME --force 
          else
            echo "Bucket not found or already deleted."
          fi

      - name: Delete CloudFormation Stack
        run: |
          aws cloudformation delete-stack --stack-name sentinel-s3-stack
          echo "Waiting for stack deletion..."
          aws cloudformation wait stack-delete-complete --stack-name sentinel-s3-stack
